backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img
locale: "fr"

collections:
  - name: "actualites"
    label: "Actualités"
    folder: "src/pages/actualites"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date de publication", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image principale", name: "featuredimage", widget: image }
      - { label: "Article", name: "body", widget: "markdown" }
      - { label: "Afficher", name: "published", widget: "boolean" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "agenda"
    label: "Agenda"
    folder: "src/pages/agenda"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "agenda-event",
        }
      - { label: "Titre", name: "title", widget: "string" }
      - {
          label: "addresse",
          name: "address",
          widget: "string",
          required: false,
        }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Résumé", name: "resume", widget: "text", required: false }
      - {
          label: "Description",
          name: "body",
          widget: "markdown",
          required: false,
        }
      - { label: "Afficher", name: "display", widget: "boolean" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Page principale"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Citation, name: title, widget: string }
          - { label: Heading, name: heading, widget: string }
          - { label: Alerte, name: alerte, widget: string }
          - {
              label: presentation,
              name: presentation,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - {
              label: Section,
              name: intro,
              widget: object,
              fields:
                [
                  { label: En tête, name: heading, widget: string },

                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                  { label: Description, name: description, widget: text },
                ],
            }
      - file: "src/pages/association/index.md"
        label: "Association"
        name: "association"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "default-page",
            }
          - { label: Titre, name: title, widget: string }
          - {
              label: Sous-titre,
              name: subtitle,
              widget: string,
              required: false,
            }
          - { label: Description, name: description, widget: string }
          - { label: Image, name: image, widget: image, required: false }
          - { label: "Contenu", name: "body", widget: "markdown" }
      - file: "src/pages/habitat-partage/index.md"
        label: "Habitat partagé"
        name: "habitat-partage"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "default-page",
            }
          - { label: Titre, name: title, widget: string }
          - {
              label: Sous-titre,
              name: subtitle,
              widget: string,
              required: false,
            }
          - { label: Description, name: description, widget: string }
          - { label: Image, name: image, widget: image, required: false }
          - { label: "Contenu", name: "body", widget: "markdown" }
      - file: "src/pages/mentions-legales/index.md"
        label: "Mentions légales"
        name: "mentions-legales"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "default-page",
            }
          - { label: Titre, name: title, widget: string }
          - {
              label: Sous-titre,
              name: subtitle,
              widget: string,
              required: false,
            }
          - { label: Description, name: description, widget: string }
          - { label: Image, name: image, widget: image, required: false }
          - { label: "Contenu", name: "body", widget: "markdown" }
      - file: "src/pages/nous-soutenir/index.md"
        label: "Nous soutenir"
        name: "nous-soutenir"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "support-page",
            }
          - { label: Titre, name: title, widget: string }
          - {
              label: Sous-titre,
              name: subtitle,
              widget: string,
              required: false,
            }
          - { label: Description, name: description, widget: string }
          - { label: Image, name: image, widget: image, required: false }
          - { label: "Contenu", name: "body", widget: "markdown" }
          - { label: "Adhesion", name: "adhesion", widget: "text" }
          - { label: "Dons", name: "tips", widget: "text" }
      - file: "src/pages/contact/index.md"
        label: "Contact"
        name: "Contact"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact-page",
            }
          - { label: Titre, name: title, widget: string }
          - {
              label: Sous-titre,
              name: subtitle,
              widget: string,
              required: false,
            }
          - { label: Description, name: description, widget: string }
          - { label: Image, name: image, widget: image, required: false }
          - { label: "Contenu", name: "body", widget: "markdown" }
